config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'index#index'

  namespace :pixnet do
    resources :users do
      resources :articles
      put 'fetch_articles', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :articles, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

  namespace :ruten do
    resources :users do
      resources :products
      put 'fetch_products', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :products, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

end

app/models/pixnet.rb
require 'open-uri'
require 'json'
module Pixnet
  extend ActiveSupport::Concern

  def self.table_name_prefix
    'pixnet_'
  end

  module ClassMethods
    def fetch_json_data(url)
      begin
        JSON.parse(open(url).read)
      rescue OpenURI::HTTPError => error
        # Pixnet API Error Codes: http://pixnet.gitbooks.io/api-error-codes/content/
        message = error.io.status.join(' ') + ": " + JSON.parse(error.io.string)['message']
        #ErrorLog.save_record(self, url, message)
      end
    end
  end
end

app/models/pixnet/article.rb
class Pixnet::Article < ApplicationRecord
  include Pixnet
  belongs_to :user
  has_many :images, dependent: :destroy
  validates :origin_id, presence: true
  validates :user, presence: true
  before_validation :fetch_article_data, on: :create

  def detail_url
    "https://emma.pixnet.cc/blog/articles/#{self.origin_id}?" + {
      user: self.user.account,
      format: 'json',
      status: 2,
      client_id: Settings.Pixnet.consumer_key
    }.to_query
  end

  def fetch_article_data!
    fetch_article_data
    save!
  end

  def fetch_article_data
    return nil if self.origin_id.blank?

    json_object = self.class.fetch_json_data detail_url
    return nil unless json_object.is_a?(Hash)

    self.title = json_object['article']['title'].to_s
    json_object['article']['images'].each do |node|
      url = if node['url'].to_s =~ %r{^http[s]?://.+}
        node['url'].to_s # 單純 http/https 開頭
      else
        "http:#{node['url'].to_s}" # // 開頭
      end
      url_hash = Digest::MD5.hexdigest(node['url'].to_s)
      if self.new_record? #對應舊資料更新時不需要重抓一樣的圖
        self.images.build(url: url, digest: url_hash)
      else
        self.images.find_or_create_by(url: url, digest: url_hash)
      end
    end
    content_nodes = Nokogiri::HTML(json_object['article']['body'].to_s) do |config|
      config.noblanks
    end
    # Replace img tags
    content_nodes.css('img').each do |img_node|
      digest = Digest::MD5.hexdigest(img_node['src'].to_s)
      if self.images.select{|img| img.digest == digest}.try(:size) > 0
        img_node.name = 'pixnet_img'
        img_node['original_src'] = img_node['src']
        img_node['src'] = digest
      else
        puts "找不到圖 #{img_node['src']}"
      end
    end
    # Clear blank P nodes
    content_nodes.css('p').each do |x|
      x.remove if x.children.size == 1 && x.children.first.name == 'text' && x.children.first.text.blank?
    end
    self.content = Rumoji.encode(content_nodes.css('body').inner_html) # 避免emoji存進db會出錯
  end

  def html_nodes
    @html_nodes ||= Nokogiri::HTML(self.content)
  end

end

app/models/pixnet/image.rb
class Pixnet::Image < ApplicationRecord
  include Pixnet
  belongs_to :article
  mount_uploader :img, ::ArticleImgUploader

  validates :url, presence: true

  after_validation :set_image_url, on: :create

  def set_image_url
    self.remote_img_url = self.url
  end
end

app/models/pixnet/user.rb
class Pixnet::User < ApplicationRecord
  include Pixnet

  PER_PAGE = 100

  has_many :articles, dependent: :destroy

  validates_presence_of :account

  serialize :hits

  def fetch_articles
    json_object = self.class.fetch_json_data(self.articles_url)
    return nil unless json_object.is_a?(Hash)
    self.update article_count: json_object['total'].to_i
    json_object['articles'].each do |node|
      origin_id = node['id']
      unless self.articles.find_by(origin_id: origin_id)
        ::Pixnet::GetArticleDataJob.perform_later(self.id, origin_id)
      end
    end

    return self.articles.count if current_page * PER_PAGE >= self.article_count
    @current_page += 1
    fetch_articles
  end

  def fetch_base_info
    json_object = fetch_api_and_parse_json
    self.attributes = json_object["blog"].slice(*self.class.column_names)
    self
  end

  def base_info_url
    "https://emma.pixnet.cc/blog?format=json&user=#{self.account}"
  end

  def articles_url(page = current_page)
    "https://emma.pixnet.cc/blog/articles?" + {
      user: self.account,
      format: 'json',
      status: 2,
      page: page,
      per_page: PER_PAGE,
      client_id: Settings.Pixnet.consumer_key
    }.to_query
  end

  private
  def fetch_api_and_parse_json
    JSON.parse(open(base_info_url).read)
  end

  def current_page
    @current_page ||= 1
  end
end

app/models/ruten/user.rb
class Ruten::User < ApplicationRecord

  include Ruten

  has_many :products

  validates_presence_of :account, uniqueness: true
  validate :exists_in_ruten # 帳號必須是露天的賣家才可以成功儲存

  def fetch_products
    url = "#{self.index_url}&p=#{current_page}"

    html = self.class.fetch_page(url)

    product_a_tags = html.css('div.rt-store-goods-listing div.item-img a')
    product_a_tags.each do |a_tag|
      product_url = a_tag['href']
      origin_id = product_url.split('?').last
      ::Ruten::GetProductDataJob.perform_later(self.id, origin_id)

    end

    return true if product_a_tags.size < 30 # 露天網站每頁商品數最多30

    @current_page += 1
    fetch_products
  end

  def fetch_base_info
    # 賣場首頁同步商品數
    self.class.fetch_page(self.index_url) do |html|
      self.office_products_count = html.css('select.store-search-select option[@value="0"]')
                                      .text.gsub(/[^\d]/, '')
                                      .to_i
    end

    # 關於我頁面同步關於我
    self.class.fetch_page(self.about_url) do |html|
      self.about = html.css('.seller-info').to_html
    end

    # 賣家評價頁面同步評價資訊
    self.class.fetch_page(self.credit_url, 'big5') do |html|
      points = html.css('table#table63 tr')[3..-1].map { |tr| tr.css('td').last.text.strip }
      points.delete_if { |point| point == "" }
      self.good_point = points[0] # 好的評價
      self.soso_point = points[3] # 普通的評價
      self.bad_point  = points[5] # 不好的評價
    end

    self
  end

  def total_point
    if self.good_point.present? || self.bad_point.present? || self.soso_point.present?
      self.good_point.to_i + self.bad_point.to_i + self.soso_point.to_i
    end
  end

  def point_percent
    if self.total_point.present?
      ((self.good_point.to_f / self.total_point.to_f) * 100).round(2)
    end
  end

  def index_url
    "#{Settings.Ruten.host}/user/index00.php?s=#{account}"
  end

  def about_url
    "#{Settings.Ruten.host}/user/about.php?s=#{account}"
  end

  def credit_url
    "https://mybid.ruten.com.tw/credit/point?#{account}"
  end

  def current_page
    @current_page ||= 1
  end

  private
  def exists_in_ruten
    unless exist_in_ruten?
      errors.add(:account, "必須是露天拍賣已存在的賣家")
    end
  end

  def exist_in_ruten?
    begin
      self.class.fetch_page(self.index_url)
      true
    rescue Net::HTTPServerException => e
      false
    end
  end

end

app/controllers/pixnet/articles_controller.rb
class Pixnet::ArticlesController < ::ResourcesController

  def fetch_remote
    current_object.fetch_article_data!
    flash[:success] = '更新完成'
    redirect_to url_after_update
  end

  private
  def collection_scope
    if params[:user_id]
      @current_pixnet_user ||= ::Pixnet::User.find(params[:user_id])
      @current_pixnet_user.articles
    else
      ::Pixnet::Article.order(:id)
    end
  end

  def object_params
    params.require(:pixnet_article).permit(:title, :content)
  end

end

app/controllers/pixnet/users_controller.rb
class Pixnet::UsersController < ::ResourcesController

  def index
    @users = Pixnet::User.all
  end

  def fetch_articles
    flash[:notice] = '程式背景執行中'
    current_object.fetch_articles
    redirect_to url_after_update
  end

  def sync
    user = Pixnet::User.find_or_initialize_by({ account: params[:account] })

    begin
      user.fetch_base_info
      user.save!
    rescue OpenURI::HTTPError => e
      logger.error e
      flash[:error] = '同步失敗'
    rescue ActiveRecord::RecordInvalid => e
      logger.error e.message
      flash[:error] = '儲存失敗'
    else
      flash[:success] = '同步完成'
    end

    redirect_to edit_pixnet_user_path(user.id)
  end

  private
  def collection_scope
    ::Pixnet::User.order(:id)
  end

  def object_params
    params.require(:pixnet_user)
          .permit(:name, :account, :description, :keyword, :site_category)
  end

end

app/controllers/ruten/users_controller.rb
class Ruten::UsersController < ::ResourcesController

  def fetch_products
    flash[:notice] = '程式背景執行中'
    current_object.fetch_products
    redirect_to url_after_update
  end

  def sync
    @current_object = Ruten::User.find_or_initialize_by({ account: params[:account] })

    begin
      @current_object.fetch_base_info
      @current_object.save!
    rescue Net::HTTPServerException => e
      logger.error e
      flash.now[:error] = '不存在的露天帳號'
      render :new
    else
      flash[:success] = '同步完成'
      redirect_to edit_ruten_user_path(@current_object.id)
    end
  end

  private
  def collection_scope
    ::Ruten::User.order(:id)
  end

  def object_params
    params.require(:ruten_user).permit(:account, :memo)
  end

end

app/helpers/pixnet/articles_helper.rb
module Pixnet::ArticlesHelper

  def display_article(article)
    body = article.html_nodes#.css('body')
    body.css('pixnet_img').each do |img_node|
      img_node.name = 'img'
      begin
        img_node['src'] = Pixnet::Image.find_by(digest: img_node['src']).img.url
      rescue NoMethodError
        logger.info "沒圖片的 SRC= #{img_node['original_src']}"
      end
    end

    body
  end

  def pixnet_user_link(user)
    if controller_name == 'users'
      user.name
    else
      link_to user.name, pixnet_user_path(user)
    end
  end

  def pixnet_article_link(article)
    "http://#{article.user.account}.pixnet.net/blog/post/#{article.origin_id}"
  end

  def pixnet_blog_link(user)
    "http://#{user.account}.pixnet.net"
  end

  def pixnet_articles_breadcrumb user_id
    if user_id.present?
      breadcrumb('Pixnet', link_to('文章管理', (pixnet_articles_path)), current_collection.take.user.name)
    else
      breadcrumb('Pixnet', '文章管理')
    end
  end

end

app/helpers/pixnet/users_helper.rb
module Pixnet::UsersHelper
  def pixnet_blog_link(user)
    "http://#{user.account}.pixnet.net"
  end

  def formated_hits(hits)
    content = if hits.blank?
                '未同步'
              else
                "#{number_with_delimiter(hits['total'])}(總) #{number_with_delimiter(hits['weekly'])}(週) #{ number_with_delimiter(hits['daily'])}(日)"
              end
    content_tag :p, content, class: 'help-block'
  end

  def full_name(user)
    hint = user.name.blank? ? '' : " (#{user.name})"
    "#{user.account}#{hint}"
  end

  def pixnet_users_breadcrumb user_id
    if user_id.present?
      breadcrumb('Pixnet', link_to('文章管理', (pixnet_articles_path)), current_collection.take.user.name)
    else
      breadcrumb('Pixnet', '使用者管理')
    end
  end

end

app/helpers/ruten/users_helper.rb
module Ruten::UsersHelper

  def ruten_origin_button path
    link_to '賣場首頁', path, class: 'btn btn-xs btn-default', target: '_blank'
  end

  def formated_point user
    if !user.new_record? && user.good_point.present?
      "#{user.total_point}(總) #{user.good_point}(優良) #{user.soso_point}(普通) #{user.bad_point}(差) #{user.point_percent}(好評比)"
    else
      '未同步'
    end
  end

  def render_office_products_count user
    if user.office_products_count.nil?
      '未同步'
    else
      user.office_products_count.to_i
    end
  end

  def total_point_for_index user
    unless user.total_point.nil?
      link_to(user.total_point.to_i, user.credit_url, target: '_blank')
    end
  end

  def ruten_users_breadcrumb user_id
    if user_id.present?
      breadcrumb('露天拍賣', link_to("商品管理", ruten_products_path), current_collection.take.user.account)
    else
      breadcrumb('露天拍賣', '賣家管理')
    end
  end

end

app/views/pixnet/users/_form.html.erb
<div class="form-area">
  <%= simple_form_for current_object do |f| %>
  <br style="clear:both">
  <div id="account-div" class="form-group has-feedback">
    <label class="control-label" for="inputSuccess2"><abbr title="required">*</abbr> 帳號</label>
    <%= f.input_field :account, { class: 'form-control', id: 'account', disabled: !current_object.new_record? } %>
    <span id="account-span" class="glyphicon form-control-feedback" aria-hidden="true"></span>
    <span class="sr-only">(success)</span>
  </div>
  <div class="form-group">
    <%= f.input :name, label: '暱稱', label_html: { class: "control-label" }, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :keyword, label: '關鍵字', label_html: { class: "control-label" }, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :site_category, label: '分類', label_html: { class: "control-label" }, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <label class="control-label"> 點擊數</label>
    <%= formated_hits(current_object.hits)%>
    <%= f.input :description, as: :text, label: '介紹', label_html: { class: "control-label" }, input_html: { class: 'form-control',  maxlength: '140', row: '7' } %>
  </div>
  <div class="form-group">
    <%= f.button :submit, '儲存', class: 'btn btn-sm btn-success' %>
    <%=  link_to '同步並儲存', 'javascript:void(0)', id: "sync",  class: 'btn btn-sm btn-primary' %>
  </div>
  <% end %>
</div>

<script>
  ready = function() {
    $("#sync").click(function(){
      account = $('input[name="pixnet_user[account]"]').val();
      location.href = "/pixnet/users/sync/" + account;
    })

    $('input[name="pixnet_user[account]"]').blur(function(){
      var span = $("#account-span");
      var div = $("#account-div");

      $.get( "https://emma.pixnet.cc/blog?format=json&user=" + $(this).val(), function() {
        }).done(function( data ){
          span.removeClass('glyphicon-remove');
          div.removeClass('has-error');
          span.addClass('glyphicon-ok');
          div.addClass('has-success');
          $('input[type="submit"]').prop('disabled', false);
          $('#sync').attr("disabled", false);
        })
        .fail(function( data ){
          span.addClass('glyphicon-remove');
          div.addClass('has-error');
          span.removeClass('glyphicon-ok');
          div.remove('has-success');
          $('input[type="submit"]').prop('disabled', true);
          $('#sync').attr("disabled", true);
        });

    });

  }

  $(document).on('turbolinks:load', ready)
</script>

app/views/pixnet/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: 'Pixnet', title: '編輯帳號' %>
      <%= breadcrumb('Pixnet',link_to('使用者管理', pixnet_users_path), full_name(current_object)) %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pixnet/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: 'Pixnet', title: '使用者管理' %>
      <%= breadcrumb('Pixnet', '使用者管理') %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= link_to '新增帳號', new_pixnet_user_path, class: 'btn btn-sm btn-primary' %>
      <hr />
      <% if current_collection.any? %>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>帳號</th>
            <th>暱稱</th>
            <th>文章數</th>
            <th>動作</th>
          </tr>
        </thead>
        <tbody>
          <% current_collection.each_with_index do |user, num| %>
          <tr>
            <th scope="row"><%= num %></th>
            <td><%=user.account %></td>
            <td><%=user.name.html_safe %></td>
            <td><%= link_to user.articles.count, pixnet_user_articles_path(user) %></td>
            <td>
              <%= origin_button pixnet_blog_link(user) %>
              <%= fetch_button fetch_articles_pixnet_user_path(user) %>
              <%= edit_button edit_pixnet_user_path(user) %>
              <%= delete_button pixnet_user_path(user) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate current_collection %>
      <% else %>
      <%= no_data_alert %>
      <% end %>
    </div>
  </div>
</div>

app/views/pixnet/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
    <%= render "shared/caption", site: 'Pixnet', title: '新增帳號' %>
    <%= breadcrumb('Pixnet',link_to('使用者管理', pixnet_users_path), '新增帳號') %>
    <%= render 'form' %>
    </div>
  </div>

</div>