config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'index#index'

  namespace :pixnet do
    resources :users do
      resources :articles
      put 'fetch_articles', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :articles, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

  namespace :ruten do
    resources :users do
      resources :products
      put 'fetch_products', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :products, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

end

app/models/pixnet.rb
require 'open-uri'
require 'json'
module Pixnet
  extend ActiveSupport::Concern

  def self.table_name_prefix
    'pixnet_'
  end

  module ClassMethods
    def fetch_json_data(url)
      begin
        JSON.parse(open(url).read)
      rescue OpenURI::HTTPError => error
        # Pixnet API Error Codes: http://pixnet.gitbooks.io/api-error-codes/content/
        message = error.io.status.join(' ') + ": " + JSON.parse(error.io.string)['message']
        #ErrorLog.save_record(self, url, message)
      end
    end
  end
end

app/models/pixnet/article.rb
class Pixnet::Article < ApplicationRecord
  include Pixnet
  belongs_to :user
  has_many :images, dependent: :destroy
  validates :origin_id, presence: true
  validates :user, presence: true
  before_validation :fetch_article_data, on: :create

  def detail_url
    "https://emma.pixnet.cc/blog/articles/#{self.origin_id}?" + {
      user: self.user.account,
      format: 'json',
      status: 2,
      client_id: Settings.Pixnet.consumer_key
    }.to_query
  end

  def fetch_article_data!
    fetch_article_data
    save!
  end

  def fetch_article_data
    return nil if self.origin_id.blank?

    json_object = self.class.fetch_json_data detail_url
    return nil unless json_object.is_a?(Hash)

    self.title = json_object['article']['title'].to_s
    json_object['article']['images'].each do |node|
      url = if node['url'].to_s =~ %r{^http[s]?://.+}
        node['url'].to_s # 單純 http/https 開頭
      else
        "http:#{node['url'].to_s}" # // 開頭
      end
      url_hash = Digest::MD5.hexdigest(node['url'].to_s)
      if self.new_record? #對應舊資料更新時不需要重抓一樣的圖
        self.images.build(url: url, digest: url_hash)
      else
        self.images.find_or_create_by(url: url, digest: url_hash)
      end
    end
    content_nodes = Nokogiri::HTML(json_object['article']['body'].to_s) do |config|
      config.noblanks
    end
    # Replace img tags
    content_nodes.css('img').each do |img_node|
      digest = Digest::MD5.hexdigest(img_node['src'].to_s)
      if self.images.select{|img| img.digest == digest}.try(:size) > 0
        img_node.name = 'pixnet_img'
        img_node['original_src'] = img_node['src']
        img_node['src'] = digest
      else
        puts "找不到圖 #{img_node['src']}"
      end
    end
    # Clear blank P nodes
    content_nodes.css('p').each do |x|
      x.remove if x.children.size == 1 && x.children.first.name == 'text' && x.children.first.text.blank?
    end
    self.content = Rumoji.encode(content_nodes.css('body').inner_html) # 避免emoji存進db會出錯
  end

  def html_nodes
    @html_nodes ||= Nokogiri::HTML(self.content)
  end

end

app/models/pixnet/image.rb
class Pixnet::Image < ApplicationRecord
  include Pixnet
  belongs_to :article
  mount_uploader :img, ::ArticleImgUploader

  validates :url, presence: true

  after_validation :set_image_url, on: :create

  def set_image_url
    self.remote_img_url = self.url
  end
end

app/models/pixnet/user.rb
class Pixnet::User < ApplicationRecord
  include Pixnet

  PER_PAGE = 100

  has_many :articles, dependent: :destroy

  validates_presence_of :account

  serialize :hits

  def fetch_articles
    json_object = self.class.fetch_json_data(self.articles_url)
    return nil unless json_object.is_a?(Hash)
    self.update article_count: json_object['total'].to_i
    json_object['articles'].each do |node|
      origin_id = node['id']
      unless self.articles.find_by(origin_id: origin_id)
        ::Pixnet::GetArticleDataJob.perform_later(self.id, origin_id)
      end
    end

    return self.articles.count if current_page * PER_PAGE >= self.article_count
    @current_page += 1
    fetch_articles
  end

  def fetch_base_info
    json_object = fetch_api_and_parse_json
    self.attributes = json_object["blog"].slice(*self.class.column_names)
    self
  end

  def base_info_url
    "https://emma.pixnet.cc/blog?format=json&user=#{self.account}"
  end

  def articles_url(page = current_page)
    "https://emma.pixnet.cc/blog/articles?" + {
      user: self.account,
      format: 'json',
      status: 2,
      page: page,
      per_page: PER_PAGE,
      client_id: Settings.Pixnet.consumer_key
    }.to_query
  end

  private
  def fetch_api_and_parse_json
    JSON.parse(open(base_info_url).read)
  end

  def current_page
    @current_page ||= 1
  end
end

app/controllers/pixnet/articles_controller.rb
class Pixnet::ArticlesController < ::ResourcesController

  def fetch_remote
    current_object.fetch_article_data!
    flash[:success] = '更新完成'
    redirect_to url_after_update
  end

  private
  def collection_scope
    if params[:user_id]
      @current_pixnet_user ||= ::Pixnet::User.find(params[:user_id])
      @current_pixnet_user.articles
    else
      ::Pixnet::Article.order(:id)
    end
  end

  def object_params
    params.require(:pixnet_article).permit(:title, :content)
  end

end

app/controllers/pixnet/users_controller.rb
class Pixnet::UsersController < ::ResourcesController

  def index
    @users = Pixnet::User.all
  end

  def fetch_articles
    flash[:notice] = '程式背景執行中'
    current_object.fetch_articles
    redirect_to url_after_update
  end

  def sync
    user = Pixnet::User.find_or_initialize_by({ account: params[:account] })

    begin
      user.fetch_base_info
      user.save!
    rescue OpenURI::HTTPError => e
      logger.error e
      flash[:error] = '同步失敗'
    rescue ActiveRecord::RecordInvalid => e
      logger.error e.message
      flash[:error] = '儲存失敗'
    else
      flash[:success] = '同步完成'
    end

    redirect_to edit_pixnet_user_path(user.id)
  end

  private
  def collection_scope
    ::Pixnet::User.order(:id)
  end

  def object_params
    params.require(:pixnet_user)
          .permit(:name, :account, :description, :keyword, :site_category)
  end

end

app/helpers/pixnet/articles_helper.rb
module Pixnet::ArticlesHelper

  def display_article(article)
    body = article.html_nodes#.css('body')
    body.css('pixnet_img').each do |img_node|
      img_node.name = 'img'
      begin
        img_node['src'] = Pixnet::Image.find_by(digest: img_node['src']).img.url
      rescue NoMethodError
        logger.info "沒圖片的 SRC= #{img_node['original_src']}"
      end
    end

    body
  end

  def pixnet_user_link(user)
    if controller_name == 'users'
      user.name
    else
      link_to user.name, pixnet_user_path(user)
    end
  end

  def pixnet_article_link(article)
    "http://#{article.user.account}.pixnet.net/blog/post/#{article.origin_id}"
  end

  def pixnet_blog_link(user)
    "http://#{user.account}.pixnet.net"
  end

  def pixnet_articles_breadcrumb user_id
    if user_id.present?
      breadcrumb('Pixnet', link_to('文章管理', (pixnet_articles_path)), current_collection.take.user.name)
    else
      breadcrumb('Pixnet', '文章管理')
    end
  end

end

app/helpers/pixnet/users_helper.rb
module Pixnet::UsersHelper
  def pixnet_blog_link(user)
    "http://#{user.account}.pixnet.net"
  end

  def formated_hits(hits)
    content = if hits.blank?
                '未同步'
              else
                "#{number_with_delimiter(hits['total'])}(總) #{number_with_delimiter(hits['weekly'])}(週) #{ number_with_delimiter(hits['daily'])}(日)"
              end
    content_tag :p, content, class: 'help-block'
  end

  def full_name(user)
    hint = user.name.blank? ? '' : " (#{user.name})"
    "#{user.account}#{hint}"
  end

  def pixnet_users_breadcrumb user_id
    if user_id.present?
      breadcrumb('Pixnet', link_to('文章管理', (pixnet_articles_path)), current_collection.take.user.name)
    else
      breadcrumb('Pixnet', '使用者管理')
    end
  end

end

app/views/pixnet/articles/_article.html.erb
<%= simple_form_for article do |f| %>
  <%= f.input :title, label: '文章標題' %>
  <%= f.input :content, label: '文章內容' %>
  <%= submit_button f %>
<% end %>

app/views/pixnet/articles/_btn_group.html.erb
<div class="form-group btn-group">
  <%= origin_button pixnet_article_link(current_object) %>
  <%= fetch_button fetch_remote_pixnet_article_path(current_object) %>
  <%= delete_button pixnet_article_path(current_object) %>
</div>

app/views/pixnet/articles/_table.html.erb
<% if articles.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>標題</th>
      <th>作者</th>
      <th>管理</th>
    </tr>
  </thead>
  <tbody>
    <% articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= link_to article.title, pixnet_article_path(article) %></td>
      <td><%= link_to article.user.name, pixnet_user_articles_path(article.user) %></td>
      <td>
        <%= origin_button pixnet_article_link(article) %>
        <%= fetch_button fetch_remote_pixnet_article_path(article) %>
        <%= delete_button pixnet_article_path(article) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate articles %>
<% else %>
<%= no_data_alert %>
<% end %>

app/views/pixnet/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: 'Pixnet', title: '文章管理' %>
      <%= pixnet_articles_breadcrumb params['user_id'] %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'table', locals: { articles: current_collection } %>
    </div>
  </div>
</div>

app/views/pixnet/articles/show.html.erb
<div class="container">
<div class="row">
  <div class="col-lg-12">
    <%= render "shared/caption", site: 'Pixnet', title: '文章內容' %>
    <%= breadcrumb(
          'Pixnet',
          link_to("文章管理", pixnet_articles_path),
          link_to(current_object.user.name, pixnet_user_articles_path(current_object.user)),
          current_object.title
        )
    %>
  </div>
</div>
<%= render 'btn_group' %>
<%=raw display_article(current_object)%>
<hr />
<%= render 'btn_group' %>
</div>