config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'index#index'

  namespace :pixnet do
    resources :users do
      resources :articles
      put 'fetch_articles', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :articles, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

  namespace :ruten do
    resources :users do
      resources :products
      put 'fetch_products', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :products, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

end

app/models/pixnet/user.rb
class Pixnet::User < ApplicationRecord
  include Pixnet

  PER_PAGE = 100

  has_many :articles, dependent: :destroy

  validates_presence_of :account

  serialize :hits

  def fetch_articles
    json_object = self.class.fetch_json_data(self.articles_url)
    return nil unless json_object.is_a?(Hash)
    self.update article_count: json_object['total'].to_i
    json_object['articles'].each do |node|
      origin_id = node['id']
      unless self.articles.find_by(origin_id: origin_id)
        ::Pixnet::GetArticleDataJob.perform_later(self.id, origin_id)
      end
    end

    return self.articles.count if current_page * PER_PAGE >= self.article_count
    @current_page += 1
    fetch_articles
  end

  def fetch_base_info
    json_object = fetch_api_and_parse_json
    self.attributes = json_object["blog"].slice(*self.class.column_names)
    self
  end

  def base_info_url
    "https://emma.pixnet.cc/blog?format=json&user=#{self.account}"
  end

  def articles_url(page = current_page)
    "https://emma.pixnet.cc/blog/articles?" + {
      user: self.account,
      format: 'json',
      status: 2,
      page: page,
      per_page: PER_PAGE,
      client_id: Settings.Pixnet.consumer_key
    }.to_query
  end

  private
  def fetch_api_and_parse_json
    JSON.parse(open(base_info_url).read)
  end

  def current_page
    @current_page ||= 1
  end
end

app/models/ruten.rb
module Ruten
  extend ActiveSupport::Concern

  def self.table_name_prefix
    'ruten_'
  end

  module ClassMethods
    def fetch_page(url, char = nil)
      uri = URI(url)
      request = Net::HTTP::Get.new(uri.request_uri, {'User-Agent' => Settings.user_agents.sample})
      http = Net::HTTP.new(uri.host, 80)
      cookie = CGI::Cookie.new(Settings.Ruten.cookie_key, Settings.Ruten.cookie_value)

      request['Cookie'] = cookie.to_s
      response = http.request(request)
      response.error! if response.code != "200"
      body = if char.nil?
               response.body
             else
               response.body.force_encoding('big5').encode('UTF-8')
             end
      html = Nokogiri::HTML(body)
      yield(html) if block_given?

      html
    end
  end
end

app/models/ruten/product.rb
class Ruten::Product < ApplicationRecord
  include Ruten

  belongs_to :user, :counter_cache => true

  validates :origin_id, presence: true, uniqueness: true
  validates :title, presence: true
  validates :user, presence: true

  before_validation :fetch_remote_data, on: :create

  mount_uploader :main_img, ::RutenProductImageUploader

  def detail_url
    "http://goods.ruten.com.tw/item/show?#{self.origin_id}"
  end

  def fetch_remote_data!
    fetch_remote_data
    save!
  end

  def fetch_remote_data
    return nil if self.origin_id.blank?
    html = self.class.fetch_page detail_url

    self.title = html.css('div .main-content h1').first.text
    self.price = html.css('strong.price').text.delete(',')
    self.sale_out_num = html.css('table.item-detail-table tr td')[1].text.strip
    self.pay_way = html.css('table.item-detail-table tr td')[3].text.strip.gsub(/\n/,'').split.join(' / ')
    self.transport_way = html.css('table.item-detail-table tr td')[5].text.strip.split("\n").first
    self.situation = html.css('ul#product-memo li')[0].text.split('：').last.delete(' ')
    self.location = html.css('ul#product-memo li')[1].text.split('：').last.delete(' ')
    self.launched_date = html.css('ul#product-memo li')[2].text.split('：').last.gsub(/^ /,'')
    self.remote_main_img_url = html.css('div.item-gallery-main-image img').first['src'].gsub('_m.', '.')
  end

end

app/models/ruten/user.rb
class Ruten::User < ApplicationRecord

  include Ruten

  has_many :products

  validates_presence_of :account, uniqueness: true
  validate :exists_in_ruten # 帳號必須是露天的賣家才可以成功儲存

  def fetch_products
    url = "#{self.index_url}&p=#{current_page}"

    html = self.class.fetch_page(url)

    product_a_tags = html.css('div.rt-store-goods-listing div.item-img a')
    product_a_tags.each do |a_tag|
      product_url = a_tag['href']
      origin_id = product_url.split('?').last
      ::Ruten::GetProductDataJob.perform_later(self.id, origin_id)

    end

    return true if product_a_tags.size < 30 # 露天網站每頁商品數最多30

    @current_page += 1
    fetch_products
  end

  def fetch_base_info
    # 賣場首頁同步商品數
    self.class.fetch_page(self.index_url) do |html|
      self.office_products_count = html.css('select.store-search-select option[@value="0"]')
                                      .text.gsub(/[^\d]/, '')
                                      .to_i
    end

    # 關於我頁面同步關於我
    self.class.fetch_page(self.about_url) do |html|
      self.about = html.css('.seller-info').to_html
    end

    # 賣家評價頁面同步評價資訊
    self.class.fetch_page(self.credit_url, 'big5') do |html|
      points = html.css('table#table63 tr')[3..-1].map { |tr| tr.css('td').last.text.strip }
      points.delete_if { |point| point == "" }
      self.good_point = points[0] # 好的評價
      self.soso_point = points[3] # 普通的評價
      self.bad_point  = points[5] # 不好的評價
    end

    self
  end

  def total_point
    if self.good_point.present? || self.bad_point.present? || self.soso_point.present?
      self.good_point.to_i + self.bad_point.to_i + self.soso_point.to_i
    end
  end

  def point_percent
    if self.total_point.present?
      ((self.good_point.to_f / self.total_point.to_f) * 100).round(2)
    end
  end

  def index_url
    "#{Settings.Ruten.host}/user/index00.php?s=#{account}"
  end

  def about_url
    "#{Settings.Ruten.host}/user/about.php?s=#{account}"
  end

  def credit_url
    "https://mybid.ruten.com.tw/credit/point?#{account}"
  end

  def current_page
    @current_page ||= 1
  end

  private
  def exists_in_ruten
    unless exist_in_ruten?
      errors.add(:account, "必須是露天拍賣已存在的賣家")
    end
  end

  def exist_in_ruten?
    begin
      self.class.fetch_page(self.index_url)
      true
    rescue Net::HTTPServerException => e
      false
    end
  end

end

app/controllers/pixnet/users_controller.rb
class Pixnet::UsersController < ::ResourcesController

  def index
    @users = Pixnet::User.all
  end

  def fetch_articles
    flash[:notice] = '程式背景執行中'
    current_object.fetch_articles
    redirect_to url_after_update
  end

  def sync
    user = Pixnet::User.find_or_initialize_by({ account: params[:account] })

    begin
      user.fetch_base_info
      user.save!
    rescue OpenURI::HTTPError => e
      logger.error e
      flash[:error] = '同步失敗'
    rescue ActiveRecord::RecordInvalid => e
      logger.error e.message
      flash[:error] = '儲存失敗'
    else
      flash[:success] = '同步完成'
    end

    redirect_to edit_pixnet_user_path(user.id)
  end

  private
  def collection_scope
    ::Pixnet::User.order(:id)
  end

  def object_params
    params.require(:pixnet_user)
          .permit(:name, :account, :description, :keyword, :site_category)
  end

end

app/controllers/ruten/products_controller.rb
class Ruten::ProductsController < ::ResourcesController

  def fetch_remote
    current_object.fetch_remote_data!
    flash[:success] = '更新完成'
    redirect_to url_after_update
  end

  private
  def collection_scope
    if params[:user_id]
      ::Ruten::User.find(params[:user_id]).products
    else
      ::Ruten::Product.order(:id)
    end
  end

  def object_params
    params.require(:pixnet_article).permit(:title, :content)
  end
end

app/controllers/ruten/users_controller.rb
class Ruten::UsersController < ::ResourcesController

  def fetch_products
    flash[:notice] = '程式背景執行中'
    current_object.fetch_products
    redirect_to url_after_update
  end

  def sync
    @current_object = Ruten::User.find_or_initialize_by({ account: params[:account] })

    begin
      @current_object.fetch_base_info
      @current_object.save!
    rescue Net::HTTPServerException => e
      logger.error e
      flash.now[:error] = '不存在的露天帳號'
      render :new
    else
      flash[:success] = '同步完成'
      redirect_to edit_ruten_user_path(@current_object.id)
    end
  end

  private
  def collection_scope
    ::Ruten::User.order(:id)
  end

  def object_params
    params.require(:ruten_user).permit(:account, :memo)
  end

end

app/helpers/pixnet/users_helper.rb
module Pixnet::UsersHelper
  def pixnet_blog_link(user)
    "http://#{user.account}.pixnet.net"
  end

  def formated_hits(hits)
    content = if hits.blank?
                '未同步'
              else
                "#{number_with_delimiter(hits['total'])}(總) #{number_with_delimiter(hits['weekly'])}(週) #{ number_with_delimiter(hits['daily'])}(日)"
              end
    content_tag :p, content, class: 'help-block'
  end

  def full_name(user)
    hint = user.name.blank? ? '' : " (#{user.name})"
    "#{user.account}#{hint}"
  end

  def pixnet_users_breadcrumb user_id
    if user_id.present?
      breadcrumb('Pixnet', link_to('文章管理', (pixnet_articles_path)), current_collection.take.user.name)
    else
      breadcrumb('Pixnet', '使用者管理')
    end
  end

end

app/helpers/ruten/products_helper.rb
module Ruten::ProductsHelper
  def ruten_user_link(user)
    if controller_name == 'users'
      user.name
    else
      link_to user.name, pixnet_user_path(user)
    end
  end


  def ruten_products_breadcrumb user_id
    if user_id.present?
      breadcrumb('露天拍賣', link_to("商品管理", ruten_products_path), current_collection.take.user.account)
    else
      breadcrumb('露天拍賣', '商品管理')
    end
  end
end

app/helpers/ruten/users_helper.rb
module Ruten::UsersHelper

  def ruten_origin_button path
    link_to '賣場首頁', path, class: 'btn btn-xs btn-default', target: '_blank'
  end

  def formated_point user
    if !user.new_record? && user.good_point.present?
      "#{user.total_point}(總) #{user.good_point}(優良) #{user.soso_point}(普通) #{user.bad_point}(差) #{user.point_percent}(好評比)"
    else
      '未同步'
    end
  end

  def render_office_products_count user
    if user.office_products_count.nil?
      '未同步'
    else
      user.office_products_count.to_i
    end
  end

  def total_point_for_index user
    unless user.total_point.nil?
      link_to(user.total_point.to_i, user.credit_url, target: '_blank')
    end
  end

  def ruten_users_breadcrumb user_id
    if user_id.present?
      breadcrumb('露天拍賣', link_to("商品管理", ruten_products_path), current_collection.take.user.account)
    else
      breadcrumb('露天拍賣', '賣家管理')
    end
  end

end

app/views/ruten/users/_form.html.erb
<div class="form-area">
  <%= simple_form_for current_object do |f| %>
  <br style="clear:both">
  <div id="account-div" class="form-group has-feedback">
    <label class="control-label" for="inputSuccess2"><abbr title="required">*</abbr> 帳號</label>
    <%= f.input_field :account, { class: 'form-control', id: 'account', disabled: !current_object.new_record? } %>
    <span id="account-span" class="glyphicon form-control-feedback" aria-hidden="true"></span>
    <span class="sr-only">(success)</span>
  </div>
  <div class="form-group">
    <label class="control-label">已抓取商品數</label>
    <p class="help-block"><%= current_object.products_count.to_i %> </p>
  </div>
  <div class="form-group">
    <label class="control-label">露天商品數</label>
    <p class="help-block"><%= render_office_products_count current_object %> </p>
  </div>
  <div class="form-group">
    <label class="control-label">賣家評價</label>
    <p class="help-block"><%= formated_point(current_object) %> </p>
  </div>
  <div class="form-group">
    <%= f.input :memo, label: '備註', label_html: { class: "control-label" }, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.button :submit, '儲存', class: 'btn btn-sm btn-success' %>
    <%=  link_to '同步並儲存', 'javascript:void(0)', id: "sync",  class: 'btn btn-sm btn-primary' %>
  </div>
  <% end %>
</div>

<script>
  $("#sync").click(function(){
    account = $('input[name="ruten_user[account]"]').val();
    location.href = "/ruten/users/sync/" + account;
  })
</script>

app/views/ruten/users/_table.html.erb
<%= link_to '新增帳號', new_ruten_user_path, class: 'btn btn-sm btn-primary' %>
<hr />
<% if current_collection.any? %>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>帳號</th>
      <th>露天商品數</th>
      <th>已抓取商品數</th>
      <th>評價數</th>
      <th>正評比</th>
      <th>備註</th>
      <th>動作</th>
    </tr>
  </thead>
  <tbody>
    <% current_collection.each_with_index do |user, num| %>
    <tr>
      <th scope="row"><%= num %></th>
      <td><%=user.account %></td>
      <td><%=user.office_products_count %></td>
      <td><%=link_to(user.products_count.to_i, ruten_user_products_path(user)) %></td>
      <td><%= total_point_for_index(user)%></td>
      <td><%= user.point_percent.to_s %></td>
      <td><%=user.memo %></td>
      <td>
        <%= ruten_origin_button user.index_url %>
        <%= fetch_button fetch_products_ruten_user_path(user) %>
        <%= edit_button edit_ruten_user_path(user) %>
        <%= delete_button ruten_user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate current_collection %>
<% else %>
<%= no_data_alert %>
<% end %>

app/views/ruten/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: '露天拍賣', title: '編輯賣家' %>

    <%= breadcrumb('露天拍賣', link_to("賣家管理", ruten_users_path), current_object.account) %>
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/ruten/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: '露天拍賣', title: '賣家管理' %>

      <%= ruten_users_breadcrumb(params['user_id'])%>

    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'table', locals: { articles: current_collection } %>
    </div>
  </div>
</div>

app/views/ruten/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render "shared/caption", site: '露天拍賣', title: '新增賣家帳號' %>

    <%= breadcrumb('露天拍賣', link_to("賣家管理", ruten_users_path), '新增帳號') %>
    <%= render 'form' %>
    </div>
  </div>

</div>