config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'index#index'

  namespace :pixnet do
    resources :users do
      resources :articles
      put 'fetch_articles', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :articles, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

  namespace :ruten do
    resources :users do
      resources :products
      put 'fetch_products', on: :member
      get 'sync/:account'  => "users#sync", on: :collection
    end

    resources :products, except: [:new, :create] do
      put 'fetch_remote', on: :member
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class type
    flash_type_mapping[type.to_sym]
  end

  def flash_type_mapping
    {
      error:   'alert-danger',
      notice:  'alert-info',
      success: 'alert-success',
      wraning: 'alert-warning',
    }
  end

  def breadcrumb *items
    content_tag(:ol, class: 'breadcrumb') do
      concat content_tag(:li, link_to("Home", root_path))
      items.each_with_index do |item, index|
        if index == items.size - 1
          concat content_tag(:li, item, class: 'active')
        else
          concat content_tag(:li, item)
        end
      end
    end
  end

  def show_button path
    link_to '檢視', path, class: 'btn btn-xs btn-primary' if params[:action] != 'show'
  end

  def edit_button path
    link_to '編輯', path, class: 'btn btn-xs btn-success' if params[:action] != 'edit'
  end

  def delete_button path
    link_to '刪除', path, {
      method: :delete,
      class: 'btn btn-xs btn-danger',
      data: { confirm: '關聯資料也會一併刪除，確定嗎？' }
    }
  end

  def fetch_button path
    link_to '重抓資料', path, class: 'btn btn-xs btn-warning', method: :put
  end

  def origin_button path
    link_to '原始網址', path, class: 'btn btn-xs btn-default', target: '_blank'
  end

  def submit_button form
    form.button :submit, '送出', class: 'btn btn-sm btn-success'
  end

  def no_data_alert
    content_tag :div, '尚無資料', class: 'alert alert-warning'
  end

  def local_time timestamp
    timestamp.in_time_zone('Taipei').strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/views/application/_flash.html.erb
<% flash.each do |flash_type, message| %>
<div class="alert <%= alert_class(flash_type) %> alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="index.html">Crawler</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("About", root_path) %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pixnet<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "使用者管理", pixnet_users_path %></li>
            <li><%= link_to "文章列表", pixnet_articles_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">露天拍賣<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "賣家管理", ruten_users_path %></li>
            <li><%= link_to "商品列表", ruten_products_path %></li>
          </ul>
        </li>
        <li>
          <a href="contact.html">Log</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>